version: 0.2
phases:
    install:
        runtime-versions:
            java: corretto8
        commands:
            - echo In install phase ...
            # - yum update -y
            - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)
            - java -version
    pre_build:
        commands:
            - echo In pre_build phase ...
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo In build phase ...
            - echo Build started on `date`
            - echo Building the Docker image... 
            - pwd
            - ls -al
            # - cd flink-code # if zip file have include the parent folder
            - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flink-benchmark:1.13-java8-x86 .
            - docker image ls
        finally:
            - echo Build completed on `date`
    post_build:
        commands:
            - echo In post_build phase ...
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flink-benchmark:1.13-java8-x86